In [51]:
import torch
import numpy as np
import time

# Check if CUDA is available
if torch.cuda.is_available():
    device = torch.device('cuda')
    print(f"Device: {device}")
    
    # Get the name of the GPU
    gpu_name = torch.cuda.get_device_name(0)
    print(f"GPU Name: {gpu_name}")
    
    # Get the number of GPUs available
    num_gpus = torch.cuda.device_count()
    print(f"Number of GPUs: {num_gpus}")
    
    # Get the properties of the GPU
    gpu_properties = torch.cuda.get_device_properties(0)
    total_memory = gpu_properties.total_memory
    available_memory = total_memory - torch.cuda.memory_allocated(0)
    print(f"Total Memory: {total_memory / (1024 ** 3):.2f} GB")
    print(f"Available Memory: {available_memory / (1024 ** 3):.2f} GB")
else:
    print("CUDA is not available.")

Device: cuda
GPU Name: NVIDIA GeForce RTX 4050 Laptop GPU
Number of GPUs: 1
Total Memory: 6.00 GB
Available Memory: 6.00 GB


In [52]:
# The below method has 3 arguments
# 1. low - The lower bound of the range
# 2. high - The upper bound of the range
# 3. size - The shape of the tensor
# output - Returns a tensor filled with random integers generated uniformly between low and high
randint = torch.randint(-100,100,(6,))
randint

tensor([ 98, -23, -72, -60,  64, -71])

In [53]:
# We are creating a 3x2 tensor with random integers
tensor = torch.tensor([[0.1,0.2],[2.2,3.1],[4.9,5.2]])
tensor

tensor([[0.1000, 0.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [54]:
# This method creates a tensor filled with zeros
zeroes = torch.zeros(2,3)
zeroes

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [55]:
# This method creates a tensor filled with ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [56]:
# The torch.empty method creates a tensor filled with uninitialized data so whatever values are in the memory will be used
input = torch.empty(2,3)
input

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.0286e-38]])

In [57]:
# The arange method creates a 1-D tensor of size 5 with values from 0 to 4
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [58]:
# The linspace method creates a 1-D tensor of size 5 with values from 3 to 10
linspace = torch.linspace(3,10,steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [59]:
# The logspace method creates a 1-D tensor of size 5 with values from 10^-10 to 10^10
logspace = torch.logspace(start=-10,end=10,steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [60]:
# The eye method creates a 2-D tensor with ones on the diagonal and zeros elsewhere
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [61]:
# The below lines of code are used to create tensors of the same shape as the input tensor
a = torch.empty((2,3),dtype=torch.int64)
# The empty_like method creates a tensor with the same shape as the input tensor
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [62]:
# This will print the current time
start_time = time.time()
# matrix operations here 
zeroes = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"Time taken for the operation is {elapsed_time} seconds")

Time taken for the operation is 0.0 seconds


In [ ]:
# We create  a 2D tensor with random values using torch
torch_rand1 = torch.rand(10000,10000).to(device)
torch_rand2 = torch.rand(10000,10000).to(device)
# We create a 2D matrix with random values using numpy
np_rand1 = torch.rand(10000,10000)
np_rand2 = torch.rand(10000,10000)

# For the GPU
start_time = time.time()
rand = (torch_rand1 @ torch_rand2) # we do matrix operation using (@) - multiply matrices
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

# For the CPU
start_time = time.time()
rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.02179933
0.12754035


In [77]:
# We create  a 2D tensor with random values using torch
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
# We create a 2D matrix with random values using numpy
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

# For the GPU
start_time = time.time()
rand = (torch_rand1 @ torch_rand2) # we do matrix operation using (@) - multiply matrices
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

# For the CPU
start_time = time.time()
rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

# The CPU took half a second than the GPU took

0.02101421
0.13012052


* cpu time - How long it takes to run the code on the CPU - The only thing that the cpu time doesn't include is how long you have to wait
* Wall time - How long you have to wait

In [76]:
%%time 
start_time = time.time()
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00000000
CPU times: total: 0 ns
Wall time: 0 ns
