In [1]:
import torch

In [3]:
# The below method has 3 arguments
# 1. low - The lower bound of the range
# 2. high - The upper bound of the range
# 3. size - The shape of the tensor
# output - Returns a tensor filled with random integers generated uniformly between low and high
randint = torch.randint(-100,100,(6,))
randint

tensor([-41,  -5, -90, -25,  38,  70])

In [7]:
# We are creating a 3x2 tensor with random integers
tensor = torch.tensor([[0.1,0.2],[2.2,3.1],[4.9,5.2]])
tensor

tensor([[0.1000, 0.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [11]:
zeroes = torch.zeros(2,3)
zeroes

tensor([[0., 0., 0.],
        [0., 0., 0.]])